<?php
define('DATACITE_DOI_URL', 'mds.datacite.org/doi');

function islandora_doi_menu() {
  $items = array();
  $items['admin/settings/islandora_doi'] = array(
    'title' => t('Islandora DOI'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_doi_admin'),
    'access arguments' => array('administer islandora doi'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

function islandora_doi_perm() {
  return array('administer islandora doi');
}

function islandora_doi_admin() {
  $form = array();
  
  $form['islandora_doi_prefix'] = array(
    '#type' => 'textfield',
    '#title' => t('DOI Prefix'),
    '#default_value' => variable_get('islandora_doi_prefix', ''),
  );
  
  $form['islandora_doi_username'] = array(
    '#type' => 'textfield',
    '#title' => t('DataCite Username'),
    '#default_value' => variable_get('islandora_doi_username', ''),
  );
  
  $form['islandora_doi_password'] = array(
    '#type' => 'textfield',
    '#title' => t('DataCite Password'),
    '#default_value' => variable_get('islandora_doi_password', ''),
  );
  
  return system_settings_form($form);
}

function islandora_doi_mint($doi, $url) {
  $prefix = variable_get('islandora_doi_prefix', '');
  $doi = $prefix . '/' . $doi;
  
  $data = drupal_query_string_encode(array('doi' => $doi, 'url' => $url));
  
  $request_url = 'https://' . variable_get('islandora_doi_username', '') . ':' . variable_get('islandora_doi_password', '') . '@' . DATACITE_DOI_URL;
  
  $response = drupal_http_request($request_url, array('Content-Type' => 'application/x-www-form-urlencoded', 'charset' => 'UTF-8'), 'POST', $data);
  
  if ($response->code == '201') {
    return TRUE;
  }
  else {
    watchdog('islandora_doi', 'DOI mint failed: ' . $response->data);
    return FALSE;
  }
}

function islandora_doi_form_alter(&$form, &$form_state, $form_id) {
  if (!empty($form['DOI'])) {
    $form['#submit'][] = 'islandora_doi_form_submit';
  }
}

function islandora_doi_form_submit($form, &$form_state) {
  if (!empty($form_state['values']['DOI']) && !empty($form_state['values']['pid'])) {
    global $base_url;
    $object_url = 'http://conferences.dtu.dk' . '/fedora/repository/' . $form_state['values']['pid']; // hardcoded for test
    //$object_url = $base_url . '/fedora/repository/' . $form_state['values']['pid'];
    $ret = islandora_doi_mint($form_state['values']['DOI'], $object_url);
    if ($ret) {
      drupal_set_message('DOI: ' . variable_get('islandora_doi_prefix', '') . '/' . check_plain($form_state['values']['DOI']) . ' minted for: ' . $object_url); //@TODO: parameterize
    }
    //@TODO: update metadata with doi?
  }
}